default:
  path: /
  defaults: { _controller: AppBundle:Default:index }
  methods: [GET]

create:
  path: /
  defaults: { _controller: AppBundle:Default:create }
  methods: [POST]

test:
  path: /test
  defaults: { _controller: AppBundle:Default:test }
  methods: [GET]